import 'dart:math' as math;
import 'dart:typed_data';

/// Pure-Dart Whisper log-mel spectrogram.
///
/// Reproduces openai-whisper `log_mel_spectrogram` exactly:
///   * `torch.stft(n_fft=400, hop_length=160, window=hann_window(400),
///     center=True)` — center padding is REFLECT by n_fft//2 on each side;
///   * power = |stft[..., :-1]|^2  (drop the final STFT frame);
///   * mel = filters[80,201] @ power;
///   * log10(clamp(mel, 1e-10));
///   * clamp to (max - 8.0); then (x + 4.0) / 4.0.
///
/// The 80×201 Slaney mel filterbank is bundled as an asset (generated by
/// `tool/gen_mel_filters.py`, == librosa.filters.mel(16000, 400, 80)) so it
/// matches OpenAI bit-for-bit and is never recomputed at runtime.
///
/// The native SDK `WhisperWrapper` mel is NOT exposed to Flutter, hence this
/// port (GATE-2 decision 2).
class LogMel {
  LogMel(this._filters) {
    assert(_filters.length == nMels * nFreqs,
        'filterbank must be $nMels*$nFreqs floats, got ${_filters.length}');
    // Periodic Hann window of length n_fft (matches torch hann_window default).
    _window = Float64List(nFft);
    for (int n = 0; n < nFft; n++) {
      _window[n] = 0.5 - 0.5 * math.cos(2 * math.pi * n / nFft);
    }
    // Precompute DFT twiddle tables for the 201 retained bins (real input,
    // direct DFT — n_fft=400 is not a power of two; correctness over an FFT).
    _cos = List<Float64List>.generate(nFreqs, (int k) {
      final Float64List row = Float64List(nFft);
      for (int n = 0; n < nFft; n++) {
        row[n] = math.cos(-2 * math.pi * k * n / nFft);
      }
      return row;
    });
    _sin = List<Float64List>.generate(nFreqs, (int k) {
      final Float64List row = Float64List(nFft);
      for (int n = 0; n < nFft; n++) {
        row[n] = math.sin(-2 * math.pi * k * n / nFft);
      }
      return row;
    });
  }

  static const int nFft = 400;
  static const int hop = 160;
  static const int nMels = 80;
  static const int nFreqs = nFft ~/ 2 + 1; // 201

  /// Flattened [80,201] filterbank, row-major (mel-major).
  final Float32List _filters;
  late final Float64List _window;
  late final List<Float64List> _cos;
  late final List<Float64List> _sin;

  /// Frame count for a given input length, matching torch.stft(center=True)
  /// then dropping the last frame.
  static int frameCountFor(int audioLength) {
    final int padded = audioLength + 2 * (nFft ~/ 2);
    return 1 + (padded - nFft) ~/ hop - 1; // -1 == stft[..., :-1]
  }

  /// Computes the log-mel spectrogram. Returns a [LogMelResult] holding a
  /// row-major [80, frames] Float32List (index = mel*frames + frame), suitable
  /// to feed the encoder as `[1, 80, frames]`.
  LogMelResult compute(Float32List audio) {
    final int pad = nFft ~/ 2;
    final Float64List padded = _reflectPad(audio, pad);
    final int frames = 1 + (padded.length - nFft) ~/ hop - 1;

    final Float64List power = Float64List(nFreqs);
    final Float64List logRow = Float64List(nMels * frames);
    double gMax = -1e30;

    // log10(1e-10) — the value every mel bin of an all-zero frame collapses to
    // (power 0 -> clamp 1e-10 -> log10). The 30 s span padding makes most
    // frames pure silence, so we skip the DFT for them (Tier B lever; exact).
    const double zeroLog = -10.0;

    final Float64List seg = Float64List(nFft);
    for (int t = 0; t < frames; t++) {
      final int s = t * hop;
      bool nonZero = false;
      for (int n = 0; n < nFft; n++) {
        if (padded[s + n] != 0) {
          nonZero = true;
          break;
        }
      }
      if (!nonZero) {
        for (int m = 0; m < nMels; m++) {
          logRow[m * frames + t] = zeroLog;
        }
        if (zeroLog > gMax) gMax = zeroLog;
        continue;
      }
      for (int n = 0; n < nFft; n++) {
        seg[n] = padded[s + n] * _window[n];
      }
      for (int k = 0; k < nFreqs; k++) {
        final Float64List ck = _cos[k];
        final Float64List sk = _sin[k];
        double re = 0, im = 0;
        for (int n = 0; n < nFft; n++) {
          final double v = seg[n];
          re += v * ck[n];
          im += v * sk[n];
        }
        power[k] = re * re + im * im;
      }
      for (int m = 0; m < nMels; m++) {
        final int base = m * nFreqs;
        double acc = 0;
        for (int k = 0; k < nFreqs; k++) {
          acc += _filters[base + k] * power[k];
        }
        if (acc < 1e-10) acc = 1e-10;
        final double lv = _log10(acc);
        logRow[m * frames + t] = lv;
        if (lv > gMax) gMax = lv;
      }
    }

    final double floor = gMax - 8.0;
    final Float32List out = Float32List(nMels * frames);
    for (int i = 0; i < out.length; i++) {
      double lv = logRow[i];
      if (lv < floor) lv = floor;
      out[i] = ((lv + 4.0) / 4.0);
    }
    return LogMelResult(out, frames);
  }

  static final double _ln10 = math.log(10);
  static double _log10(double x) => math.log(x) / _ln10;

  /// NumPy/torch `reflect` padding: reflects WITHOUT repeating the edge sample.
  static Float64List _reflectPad(Float32List a, int p) {
    final int n = a.length;
    final Float64List out = Float64List(n + 2 * p);
    for (int i = 0; i < p; i++) {
      out[i] = a[p - i]; // left:  a[p], a[p-1], ..., a[1]
    }
    for (int i = 0; i < n; i++) {
      out[p + i] = a[i];
    }
    for (int i = 0; i < p; i++) {
      out[p + n + i] = a[n - 2 - i]; // right: a[n-2], a[n-3], ...
    }
    return out;
  }
}

class LogMelResult {
  const LogMelResult(this.data, this.frames);

  /// Row-major [80, frames] (index = mel*frames + frame).
  final Float32List data;
  final int frames;
}
